### ISSUE TITLE
Sitemap plan

### ISSUE THREAD

**Issue by rennys66** [mocaspike150/mocaspike150-theme#4]
![sitemap1](https://user-images.githubusercontent.com/46349226/53464903-f1fd1800-3a19-11e9-879f-786f8bf2d485.JPG)

**Comment by ontouchstart** [comment]
Here is the yaml version of your map, which can be used by Jekyll to generate the site

```yaml
Homepage:
  - header:
    - About Us:
      - Museum of Chinese in America
      - MOCA Spike 150
      - How to Participate
    - Events:
      - Calendar of Events:
        - Event1
        - Event2
        - Event3
      - Articles:
        - Article1
        - Article2
        - Article3
      - Photo gallery:
        - Gallery1
        - Gallery2
    - Spike Virtual Relay:
      - Running Clubs:
        - Running club1
        - Running club2
        - Running club3
    - TCS New York City Marathon:
      - Our Team:
        - Runner1
        - Runner2
        - Runner3
      - Training
      - Meet our Coach
      - FAQ
    - 150 Stories:
      - Story1
      - Story2
      - Story3
    - Donation
  - content:
    - Hero image with short message
    - Virtual Relay Map
    - Latest Events
    - NYC Marathon Count down
    - Newsletter sign up

  - footer:
    - Contact us link
    - Donation link
    - MOCA link
    - Social Media links
```
